name: Upload Repository to strongdog2 Folder

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
  deploy:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Create strongdog2 directory and move all files into it
      - name: Reorganize files
        run: |
          mkdir strongdog3
          find . -maxdepth 1 -not -name 'strongdog3' -not -name '.' -exec mv {} strongdog3/ \;
      # Sync with S3 (only changed files will be uploaded)
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --size-only --exclude '.git*/*' --exclude '*' --include 'strongdog3/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
